export type RiskLevel='Critical'|'High'|'Medium'|'Low';
export type Project={id:string;projectCode:string;name:string;state:string;district:string;authority:string;projectType:string;lat:number;lng:number;stage:string;risk:number;delay:number;delayDays:number;confidence:number;driver:string;land:number;families:number;overdue:number;compensation:boolean;legal:number;docs:number;approval:boolean;status:string};
export const projects:Project[]=[
{id:'p1',projectCode:'NH-112-MAL-01',name:'NH-112 Expansion – Malda',state:'West Bengal',district:'Malda',authority:'NHAI',projectType:'Highway',lat:25.01,lng:88.14,stage:'Compensation',risk:87,delay:91,delayDays:54,confidence:91,driver:'Pending compensation claims',land:412,families:186,overdue:27,compensation:true,legal:8,docs:19,approval:true,status:'Intervention Required'},
{id:'p2',projectCode:'ECR-OD-07',name:'East Coast Railway Corridor',state:'Odisha',district:'Balasore',authority:'Indian Railways',projectType:'Railway',lat:21.49,lng:86.93,stage:'Award',risk:78,delay:82,delayDays:47,confidence:89,driver:'Unresolved legal cases',land:365,families:142,overdue:21,compensation:true,legal:11,docs:12,approval:false,status:'At Risk'},
{id:'p3',projectCode:'IC-BR-14',name:'North Bihar Industrial Corridor',state:'Bihar',district:'Muzaffarpur',authority:'NICDC',projectType:'Industrial Corridor',lat:26.12,lng:85.39,stage:'Objection / Hearing',risk:64,delay:68,delayDays:31,confidence:86,driver:'Stakeholder objections',land:510,families:224,overdue:14,compensation:false,legal:4,docs:9,approval:true,status:'Watch'},
{id:'p4',projectCode:'AIR-JH-03',name:'Ranchi Airport Expansion',state:'Jharkhand',district:'Ranchi',authority:'AAI',projectType:'Airport',lat:23.31,lng:85.32,stage:'Notification',risk:38,delay:42,delayDays:16,confidence:84,driver:'Documentation gap',land:188,families:74,overdue:5,compensation:false,legal:2,docs:15,approval:false,status:'Watch'},
{id:'p5',projectCode:'UP-URB-21',name:'Lucknow Urban Mobility Link',state:'Uttar Pradesh',district:'Lucknow',authority:'UP PWD',projectType:'Urban Infrastructure',lat:26.85,lng:80.95,stage:'Possession',risk:52,delay:59,delayDays:25,confidence:87,driver:'Approval pending',land:240,families:98,overdue:11,compensation:true,legal:3,docs:4,approval:true,status:'At Risk'},
{id:'p6',projectCode:'AS-HWY-08',name:'Assam Highway Resilience Project',state:'Assam',district:'Kamrup',authority:'MoRTH',projectType:'Road Expansion',lat:26.14,lng:91.74,stage:'Rehabilitation & Resettlement',risk:73,delay:76,delayDays:39,confidence:88,driver:'R&R backlog',land:331,families:201,overdue:18,compensation:true,legal:5,docs:8,approval:false,status:'At Risk'},
{id:'p7',projectCode:'WB-RLY-22',name:'Sealdah–Bongaon Capacity Upgrade',state:'West Bengal',district:'North 24 Parganas',authority:'Indian Railways',projectType:'Railway',lat:22.95,lng:88.75,stage:'Award',risk:29,delay:31,delayDays:9,confidence:82,driver:'Land ownership verification',land:94,families:42,overdue:3,compensation:false,legal:1,docs:5,approval:false,status:'On Track'}
];
export const stages=['Notification','Objection / Hearing','Compensation','Award','Possession','Rehabilitation & Resettlement','Legal / Dispute'];
export function riskLevel(r:number):RiskLevel{return r>=75?'Critical':r>=50?'High':r>=25?'Medium':'Low'}
export function calcRisk(p:Pick<Project,'overdue'|'approval'|'compensation'|'legal'|'docs'|'families'|'land'|'risk'>){const score=Math.min(100,Math.round(20+p.overdue*1.2+(p.approval?9:0)+(p.compensation?18:0)+p.legal*1.5+p.docs*.45+Math.min(10,p.families/30)+Math.min(8,p.land/100)));const delay=Math.min(.98,Math.max(.08,score/100*.92));return {riskScore:score,delayProbability:delay,predictedDelayDays:Math.round(score*.62),riskLevel:riskLevel(score)}}
export function explain(p:Project){return [{feature:'Pending Compensation',value:p.compensation,contribution:p.compensation?18.4:-2.1,direction:p.compensation?'up':'down'},{feature:'Unresolved Legal Dispute',value:p.legal,contribution:p.legal*2.02,direction:'up'},{feature:'Incomplete Documentation',value:p.docs,contribution:p.docs*.62,direction:'up'},{feature:'Approval Pending',value:p.approval,contribution:p.approval?9.3:-1.4,direction:p.approval?'up':'down'},{feature:'Affected Families',value:p.families,contribution:Math.min(7.1,p.families/26),direction:'up'},{feature:'Previous Stage Delay',value:p.overdue,contribution:Math.min(5.6,p.overdue*.21),direction:'up'},{feature:'Documentation Quality',value:100-p.docs,contribution:-3.2,direction:'down'},{feature:'Recent Compensation Progress',value:p.compensation?10:70,contribution:p.compensation?-2.4:0,direction:'down'}].sort((a,b)=>Math.abs(b.contribution)-Math.abs(a.contribution))}
export const alerts=projects.slice(0,5).map((p,i)=>({id:'a'+i,projectId:p.id,severity:i<2?'Critical':i<4?'High':'Medium',project:p.name,reason:p.driver,detected:'Today, '+(10+i)+':2'+i+' AM',action:i===0?'Resolve compensation claims':'Review intervention queue',status:i===4?'Acknowledged':'Open'}));
